#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles the SIGTERM signal.

# Trap SIGTERM (Signal 15) and execute the echo command directly
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
