#!/usr/bin/env bash
# This script displays numbers 1 to 20, adding specific "bad luck" messages using a case statement.
COUNT=1
while [ $COUNT -le 20 ]; do
    case $COUNT in
        4)
            echo "$COUNT"
            echo "bad luck from China"
            ;;
        9)
            echo "$COUNT"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$COUNT"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$COUNT"
            ;;
    esac
    COUNT=$((COUNT + 1))
done
